"""Authoritative compliance control catalog.

Fully-populated control sets for the major security frameworks, current as of
the 2024-2025 revisions:

  * NIST Cybersecurity Framework (CSF) 2.0 — all 6 functions, 22 categories,
    and 106 subcategories
  * NIST SP 800-53 Rev. 5 — the full control-family set plus the commonly
    assessed controls
  * ISO/IEC 27001:2022 — all 93 Annex A controls (4 themes)
  * SOC 2 (AICPA Trust Services Criteria, 2017 w/ 2022 points of focus) —
    all common criteria plus availability/confidentiality/processing-
    integrity/privacy criteria
  * CIS Critical Security Controls v8 — all 18
  * CIS Benchmarks (host-hardening families used by the host capability)
  * PCI DSS v4.0 — all 12 requirements
  * HIPAA Security Rule — administrative/physical/technical safeguards
  * GDPR — the security-relevant articles
  * OWASP Top 10 (2021) — all 10
  * MITRE ATT&CK (Enterprise) — all 14 tactics plus a curated technique set

Each entry is ``id -> {"framework", "title"}``. IDs are namespaced by a short
framework key (e.g. ``CSF:GV.OC-01``, ``ISO27001:A.8.24``, ``ATTACK:T1110``).
"""
from __future__ import annotations

# Each framework is defined compactly as {id_suffix: title}; the loader below
# stamps the framework name and full ID onto every entry.

_NIST_CSF_20 = {
    # GOVERN
    "GV.OC-01": "Organizational mission understood and informs cybersecurity risk management",
    "GV.OC-02": "Internal and external stakeholders understood; needs/expectations considered",
    "GV.OC-03": "Legal, regulatory, and contractual requirements are understood and managed",
    "GV.OC-04": "Critical objectives, capabilities, and services that stakeholders depend on are understood",
    "GV.OC-05": "Outcomes, capabilities, and services that the organization depends on are understood",
    "GV.RM-01": "Risk management objectives are established and agreed to by stakeholders",
    "GV.RM-02": "Risk appetite and risk tolerance statements are established and communicated",
    "GV.RM-03": "Cybersecurity risk management is integrated into enterprise risk management",
    "GV.RM-04": "Strategic direction describing appropriate risk response options is established",
    "GV.RM-05": "Lines of communication across the organization for cybersecurity risks are established",
    "GV.RM-06": "A standardized method for calculating, documenting, and prioritizing risk is established",
    "GV.RM-07": "Strategic opportunities (positive risks) are characterized and included in risk discussions",
    "GV.RR-01": "Leadership is accountable for cybersecurity risk and fosters a risk-aware culture",
    "GV.RR-02": "Roles, responsibilities, and authorities are established, communicated, and enforced",
    "GV.RR-03": "Adequate resources are allocated commensurate with the risk strategy",
    "GV.RR-04": "Cybersecurity is included in human resources practices",
    "GV.PO-01": "Policy for managing cybersecurity risks is established and communicated",
    "GV.PO-02": "Policy is reviewed, updated, communicated, and enforced to reflect changes",
    "GV.OV-01": "Cybersecurity risk management strategy outcomes are reviewed to inform direction",
    "GV.OV-02": "The risk management strategy is reviewed and adjusted for organizational coverage",
    "GV.OV-03": "Cybersecurity risk management performance is evaluated and reviewed for adjustments",
    "GV.SC-01": "A cyber supply chain risk management program is established and agreed to",
    "GV.SC-02": "Cyber supply chain roles and responsibilities are established and coordinated",
    "GV.SC-03": "Supply chain risk management is integrated into cybersecurity and enterprise risk",
    "GV.SC-04": "Suppliers are known and prioritized by criticality",
    "GV.SC-05": "Requirements to address cybersecurity risks in supply chains are established in contracts",
    "GV.SC-06": "Due diligence is performed to reduce risks before entering supplier relationships",
    "GV.SC-07": "Risks posed by suppliers and their products/services are monitored over the relationship",
    "GV.SC-08": "Relevant suppliers are included in incident planning, response, and recovery",
    "GV.SC-09": "Supply chain security is integrated into cybersecurity programs throughout the lifecycle",
    "GV.SC-10": "Supply chain risk management plans include provisions for post-partnership activities",
    # IDENTIFY
    "ID.AM-01": "Inventories of hardware managed by the organization are maintained",
    "ID.AM-02": "Inventories of software, services, and systems are maintained",
    "ID.AM-03": "Representations of authorized network communication and data flows are maintained",
    "ID.AM-04": "Inventories of services provided by suppliers are maintained",
    "ID.AM-05": "Assets are prioritized based on classification, criticality, resources, and impact",
    "ID.AM-07": "Inventories of data and corresponding metadata are maintained",
    "ID.AM-08": "Systems, hardware, software, and services are managed throughout their life cycle",
    "ID.RA-01": "Vulnerabilities in assets are identified, validated, and recorded",
    "ID.RA-02": "Cyber threat intelligence is received from information-sharing forums and sources",
    "ID.RA-03": "Internal and external threats to the organization are identified and recorded",
    "ID.RA-04": "Potential impacts and likelihoods of threats exploiting vulnerabilities are identified",
    "ID.RA-05": "Threats, vulnerabilities, likelihoods, and impacts are used to understand inherent risk",
    "ID.RA-06": "Risk responses are chosen, prioritized, planned, tracked, and communicated",
    "ID.RA-07": "Changes and exceptions are managed, assessed for impact, recorded, and tracked",
    "ID.RA-08": "Processes for receiving, analyzing, and responding to vulnerability disclosures exist",
    "ID.RA-09": "The authenticity and integrity of hardware and software are assessed before acquisition",
    "ID.RA-10": "Critical suppliers are assessed prior to acquisition",
    "ID.IM-01": "Improvements are identified from evaluations",
    "ID.IM-02": "Improvements are identified from security tests and exercises, including with suppliers",
    "ID.IM-03": "Improvements are identified from operational processes, procedures, and activities",
    "ID.IM-04": "Incident response plans and other cybersecurity plans are established and maintained",
    # PROTECT
    "PR.AA-01": "Identities and credentials for authorized users, services, and hardware are managed",
    "PR.AA-02": "Identities are proofed and bound to credentials based on the context of interactions",
    "PR.AA-03": "Users, services, and hardware are authenticated",
    "PR.AA-04": "Identity assertions are protected, conveyed, and verified",
    "PR.AA-05": "Access permissions, entitlements, and authorizations follow least privilege",
    "PR.AA-06": "Physical access to assets is managed, monitored, and enforced commensurate with risk",
    "PR.AT-01": "Personnel are provided cybersecurity awareness and training",
    "PR.AT-02": "Individuals in specialized roles are provided role-based training",
    "PR.DS-01": "The confidentiality, integrity, and availability of data-at-rest are protected",
    "PR.DS-02": "The confidentiality, integrity, and availability of data-in-transit are protected",
    "PR.DS-10": "The confidentiality, integrity, and availability of data-in-use are protected",
    "PR.DS-11": "Backups of data are created, protected, maintained, and tested",
    "PR.PS-01": "Configuration management practices are established and applied",
    "PR.PS-02": "Software is maintained, replaced, and removed commensurate with risk",
    "PR.PS-03": "Hardware is maintained, replaced, and removed commensurate with risk",
    "PR.PS-04": "Log records are generated and made available for continuous monitoring",
    "PR.PS-05": "Installation and execution of unauthorized software are prevented",
    "PR.PS-06": "Secure software development practices are integrated across the software life cycle",
    "PR.IR-01": "Networks and environments are protected from unauthorized logical access and usage",
    "PR.IR-02": "Technology assets are protected from environmental threats",
    "PR.IR-03": "Mechanisms are implemented to achieve resilience requirements in normal/adverse situations",
    "PR.IR-04": "Adequate resource capacity to ensure availability is maintained",
    # DETECT
    "DE.CM-01": "Networks and network services are monitored to find potentially adverse events",
    "DE.CM-02": "The physical environment is monitored to find potentially adverse events",
    "DE.CM-03": "Personnel activity and technology usage are monitored to find adverse events",
    "DE.CM-06": "External service provider activities and services are monitored to find adverse events",
    "DE.CM-09": "Computing hardware/software, runtime environments, and their data are monitored",
    "DE.AE-02": "Potentially adverse events are analyzed to better understand associated activities",
    "DE.AE-03": "Information is correlated from multiple sources",
    "DE.AE-04": "The estimated impact and scope of adverse events are understood",
    "DE.AE-06": "Information on adverse events is provided to authorized staff and tools",
    "DE.AE-07": "Cyber threat intelligence and other contextual information are integrated into analysis",
    "DE.AE-08": "Incidents are declared when adverse events meet the defined incident criteria",
    # RESPOND
    "RS.MA-01": "The incident response plan is executed in coordination with relevant third parties",
    "RS.MA-02": "Incident reports are triaged and validated",
    "RS.MA-03": "Incidents are categorized and prioritized",
    "RS.MA-04": "Incidents are escalated or elevated as needed",
    "RS.MA-05": "The criteria for initiating incident recovery are applied",
    "RS.AN-03": "Analysis is performed to establish what has taken place and the root cause",
    "RS.AN-06": "Actions performed during an investigation are recorded; integrity/provenance preserved",
    "RS.AN-07": "Incident data and metadata are collected; integrity and provenance are preserved",
    "RS.AN-08": "An incident's magnitude is estimated and validated",
    "RS.CO-02": "Internal and external stakeholders are notified of incidents",
    "RS.CO-03": "Information is shared with designated internal and external stakeholders",
    "RS.MI-01": "Incidents are contained",
    "RS.MI-02": "Incidents are eradicated",
    # RECOVER
    "RC.RP-01": "The recovery portion of the incident response plan is executed once initiated",
    "RC.RP-02": "Recovery actions are selected, scoped, prioritized, and performed",
    "RC.RP-03": "The integrity of backups and other restoration assets is verified before restoration",
    "RC.RP-04": "Critical mission functions and cybersecurity risk management are considered in recovery",
    "RC.RP-05": "The integrity of restored assets is verified, systems/services restored, normalcy confirmed",
    "RC.RP-06": "The end of incident recovery is declared and incident-related documentation is completed",
    "RC.CO-03": "Recovery activities and progress are communicated to designated stakeholders",
    "RC.CO-04": "Public updates on incident recovery are shared using approved methods and messaging",
}

_NIST_800_53 = {
    # families exercised or commonly assessed; existing IDs preserved
    "AC-2": "Account management",
    "AC-3": "Access enforcement",
    "AC-6": "Least privilege",
    "AC-7": "Unsuccessful logon attempts",
    "AC-11": "Device lock",
    "AC-17": "Remote access",
    "AC-18": "Wireless access",
    "AC-19": "Access control for mobile devices",
    "AC-20": "Use of external systems",
    "AT-2": "Literacy training and awareness",
    "AT-3": "Role-based training",
    "AU-2": "Event logging",
    "AU-3": "Content of audit records",
    "AU-6": "Audit record review, analysis, and reporting",
    "AU-9": "Protection of audit information",
    "AU-12": "Audit record generation",
    "CA-2": "Control assessments",
    "CA-7": "Continuous monitoring",
    "CA-8": "Penetration testing",
    "CM-2": "Baseline configuration",
    "CM-6": "Configuration settings",
    "CM-7": "Least functionality",
    "CM-8": "System component inventory",
    "CP-9": "System backup",
    "CP-10": "System recovery and reconstitution",
    "IA-2": "Identification and authentication (organizational users)",
    "IA-5": "Authenticator management",
    "IR-4": "Incident handling",
    "IR-5": "Incident monitoring",
    "IR-6": "Incident reporting",
    "IR-8": "Incident response plan",
    "MA-2": "Controlled maintenance",
    "MP-2": "Media access",
    "PE-3": "Physical access control",
    "PL-8": "Security and privacy architectures",
    "PS-4": "Personnel termination",
    "RA-3": "Risk assessment",
    "RA-5": "Vulnerability monitoring and scanning",
    "RA-7": "Risk response",
    "SA-11": "Developer testing and evaluation",
    "SC-7": "Boundary protection",
    "SC-8": "Transmission confidentiality and integrity",
    "SC-12": "Cryptographic key establishment and management",
    "SC-13": "Cryptographic protection",
    "SC-28": "Protection of information at rest",
    "SI-2": "Flaw remediation",
    "SI-3": "Malicious code protection",
    "SI-4": "System monitoring",
    "SI-7": "Software, firmware, and information integrity",
    "SR-3": "Supply chain controls and processes",
    "SR-11": "Component authenticity",
}

_ISO_27001_2022 = {
    # Organizational (A.5)
    "A.5.1": "Policies for information security",
    "A.5.2": "Information security roles and responsibilities",
    "A.5.3": "Segregation of duties",
    "A.5.4": "Management responsibilities",
    "A.5.5": "Contact with authorities",
    "A.5.6": "Contact with special interest groups",
    "A.5.7": "Threat intelligence",
    "A.5.8": "Information security in project management",
    "A.5.9": "Inventory of information and other associated assets",
    "A.5.10": "Acceptable use of information and other associated assets",
    "A.5.11": "Return of assets",
    "A.5.12": "Classification of information",
    "A.5.13": "Labelling of information",
    "A.5.14": "Information transfer",
    "A.5.15": "Access control",
    "A.5.16": "Identity management",
    "A.5.17": "Authentication information",
    "A.5.18": "Access rights",
    "A.5.19": "Information security in supplier relationships",
    "A.5.20": "Addressing information security within supplier agreements",
    "A.5.21": "Managing information security in the ICT supply chain",
    "A.5.22": "Monitoring, review and change management of supplier services",
    "A.5.23": "Information security for use of cloud services",
    "A.5.24": "Information security incident management planning and preparation",
    "A.5.25": "Assessment and decision on information security events",
    "A.5.26": "Response to information security incidents",
    "A.5.27": "Learning from information security incidents",
    "A.5.28": "Collection of evidence",
    "A.5.29": "Information security during disruption",
    "A.5.30": "ICT readiness for business continuity",
    "A.5.31": "Legal, statutory, regulatory and contractual requirements",
    "A.5.32": "Intellectual property rights",
    "A.5.33": "Protection of records",
    "A.5.34": "Privacy and protection of personal identifiable information",
    "A.5.35": "Independent review of information security",
    "A.5.36": "Compliance with policies, rules and standards for information security",
    "A.5.37": "Documented operating procedures",
    # People (A.6)
    "A.6.1": "Screening",
    "A.6.2": "Terms and conditions of employment",
    "A.6.3": "Information security awareness, education and training",
    "A.6.4": "Disciplinary process",
    "A.6.5": "Responsibilities after termination or change of employment",
    "A.6.6": "Confidentiality or non-disclosure agreements",
    "A.6.7": "Remote working",
    "A.6.8": "Information security event reporting",
    # Physical (A.7)
    "A.7.1": "Physical security perimeters",
    "A.7.2": "Physical entry",
    "A.7.3": "Securing offices, rooms and facilities",
    "A.7.4": "Physical security monitoring",
    "A.7.5": "Protecting against physical and environmental threats",
    "A.7.6": "Working in secure areas",
    "A.7.7": "Clear desk and clear screen",
    "A.7.8": "Equipment siting and protection",
    "A.7.9": "Security of assets off-premises",
    "A.7.10": "Storage media",
    "A.7.11": "Supporting utilities",
    "A.7.12": "Cabling security",
    "A.7.13": "Equipment maintenance",
    "A.7.14": "Secure disposal or re-use of equipment",
    # Technological (A.8)
    "A.8.1": "User endpoint devices",
    "A.8.2": "Privileged access rights",
    "A.8.3": "Information access restriction",
    "A.8.4": "Access to source code",
    "A.8.5": "Secure authentication",
    "A.8.6": "Capacity management",
    "A.8.7": "Protection against malware",
    "A.8.8": "Management of technical vulnerabilities",
    "A.8.9": "Configuration management",
    "A.8.10": "Information deletion",
    "A.8.11": "Data masking",
    "A.8.12": "Data leakage prevention",
    "A.8.13": "Information backup",
    "A.8.14": "Redundancy of information processing facilities",
    "A.8.15": "Logging",
    "A.8.16": "Monitoring activities",
    "A.8.17": "Clock synchronization",
    "A.8.18": "Use of privileged utility programs",
    "A.8.19": "Installation of software on operational systems",
    "A.8.20": "Networks security",
    "A.8.21": "Security of network services",
    "A.8.22": "Segregation of networks",
    "A.8.23": "Web filtering",
    "A.8.24": "Use of cryptography",
    "A.8.25": "Secure development life cycle",
    "A.8.26": "Application security requirements",
    "A.8.27": "Secure system architecture and engineering principles",
    "A.8.28": "Secure coding",
    "A.8.29": "Security testing in development and acceptance",
    "A.8.30": "Outsourced development",
    "A.8.31": "Separation of development, test and production environments",
    "A.8.32": "Change management",
    "A.8.33": "Test information",
    "A.8.34": "Protection of information systems during audit testing",
}

_SOC2_TSC = {
    "CC1.1": "COSO Principle 1: Demonstrates commitment to integrity and ethical values",
    "CC1.2": "COSO Principle 2: Board exercises oversight responsibility",
    "CC1.3": "COSO Principle 3: Management establishes structures, reporting lines, authorities",
    "CC1.4": "COSO Principle 4: Demonstrates commitment to competence",
    "CC1.5": "COSO Principle 5: Enforces accountability",
    "CC2.1": "Uses relevant, quality information to support control functioning",
    "CC2.2": "Internally communicates information, including objectives and responsibilities",
    "CC2.3": "Communicates with external parties on matters affecting controls",
    "CC3.1": "Specifies objectives to enable identification and assessment of risk",
    "CC3.2": "Identifies and analyzes risk to the achievement of objectives",
    "CC3.3": "Considers the potential for fraud in assessing risk",
    "CC3.4": "Identifies and assesses changes that could impact the system of controls",
    "CC4.1": "Selects and develops ongoing/separate evaluations of controls",
    "CC4.2": "Evaluates and communicates control deficiencies",
    "CC5.1": "Selects and develops control activities that mitigate risk",
    "CC5.2": "Selects and develops general control activities over technology",
    "CC5.3": "Deploys control activities through policies and procedures",
    "CC6.1": "Logical access security software, infrastructure, and architectures",
    "CC6.2": "Registers and authorizes new internal and external users",
    "CC6.3": "Manages access based on roles and least privilege; removes access timely",
    "CC6.4": "Restricts physical access to facilities and protected assets",
    "CC6.5": "Discontinues logical/physical protections when no longer required",
    "CC6.6": "Protects against threats from sources outside system boundaries",
    "CC6.7": "Restricts the transmission, movement, and removal of information",
    "CC6.8": "Prevents or detects and acts upon unauthorized or malicious software",
    "CC7.1": "Detects and monitors configuration changes and vulnerabilities",
    "CC7.2": "Monitors system components for anomalies indicative of malicious acts",
    "CC7.3": "Evaluates security events to determine whether they are incidents",
    "CC7.4": "Responds to identified security incidents with a defined program",
    "CC7.5": "Identifies, develops, and implements recovery from incidents",
    "CC8.1": "Authorizes, designs, develops, tests, approves, and implements changes",
    "CC9.1": "Identifies, selects, and develops risk mitigation for disruptions",
    "CC9.2": "Assesses and manages risks associated with vendors and business partners",
    "A1.1": "Maintains, monitors, and evaluates current processing capacity (availability)",
    "A1.2": "Environmental protections, backup, and recovery infrastructure (availability)",
    "A1.3": "Tests recovery plan procedures supporting system recovery (availability)",
    "C1.1": "Identifies and maintains confidential information (confidentiality)",
    "C1.2": "Disposes of confidential information to meet objectives (confidentiality)",
    "PI1.1": "Obtains/uses relevant information over processing (processing integrity)",
    "PI1.2": "Inputs are complete and accurate (processing integrity)",
    "PI1.3": "Processing is complete, accurate, timely, and authorized (processing integrity)",
    "PI1.4": "Outputs are complete and accurate (processing integrity)",
    "PI1.5": "Stores inputs/outputs completely, accurately, and timely (processing integrity)",
    "P1.1": "Provides notice about privacy practices (privacy)",
    "P2.1": "Communicates choices available regarding personal information (privacy)",
    "P3.1": "Collects personal information consistent with objectives (privacy)",
    "P4.1": "Limits use, retention, and disposal of personal information (privacy)",
    "P5.1": "Provides data subjects access to their personal information (privacy)",
    "P6.1": "Discloses personal information only for identified purposes (privacy)",
    "P7.1": "Maintains accurate, complete, and relevant personal information (privacy)",
    "P8.1": "Handles privacy inquiries, complaints, and disputes (privacy)",
}

_CIS_CONTROLS_V8 = {
    "1": "Inventory and control of enterprise assets",
    "2": "Inventory and control of software assets",
    "3": "Data protection",
    "4": "Secure configuration of enterprise assets and software",
    "5": "Account management",
    "6": "Access control management",
    "7": "Continuous vulnerability management",
    "8": "Audit log management",
    "9": "Email and web browser protections",
    "10": "Malware defenses",
    "11": "Data recovery",
    "12": "Network infrastructure management",
    "13": "Network monitoring and defense",
    "14": "Security awareness and skills training",
    "15": "Service provider management",
    "16": "Application software security",
    "17": "Incident response management",
    "18": "Penetration testing",
}

_CIS_BENCHMARKS = {
    "1.4": "Secure permissions on critical system files",
    "2.2": "Minimize exposed network services",
    "3.3": "Network kernel parameters (host hardening)",
    "4.4": "Host-based firewall configured",
    "5.2": "SSH server configuration hardening",
    "5.4": "User accounts and access controls",
}

_PCI_DSS_40 = {
    "1": "Install and maintain network security controls",
    "2": "Apply secure configurations to all system components",
    "3": "Protect stored account data",
    "4": "Protect cardholder data with strong cryptography during transmission",
    "5": "Protect all systems and networks from malicious software",
    "6": "Develop and maintain secure systems and software",
    "7": "Restrict access to system components and cardholder data by business need to know",
    "8": "Identify users and authenticate access to system components",
    "9": "Restrict physical access to cardholder data",
    "10": "Log and monitor all access to system components and cardholder data",
    "11": "Test security of systems and networks regularly",
    "12": "Support information security with organizational policies and programs",
}

_HIPAA_SECURITY = {
    "164.308(a)(1)": "Security management process (risk analysis and risk management)",
    "164.308(a)(3)": "Workforce security",
    "164.308(a)(4)": "Information access management",
    "164.308(a)(5)": "Security awareness and training",
    "164.308(a)(6)": "Security incident procedures",
    "164.308(a)(7)": "Contingency plan",
    "164.310(a)(1)": "Facility access controls",
    "164.310(d)(1)": "Device and media controls",
    "164.312(a)(1)": "Access control (technical)",
    "164.312(b)": "Audit controls",
    "164.312(c)(1)": "Integrity of ePHI",
    "164.312(d)": "Person or entity authentication",
    "164.312(e)(1)": "Transmission security",
}

_GDPR = {
    "Art5": "Principles relating to processing of personal data",
    "Art25": "Data protection by design and by default",
    "Art30": "Records of processing activities",
    "Art32": "Security of processing",
    "Art33": "Notification of a personal data breach to the supervisory authority",
    "Art34": "Communication of a personal data breach to the data subject",
    "Art35": "Data protection impact assessment",
}

_OWASP_TOP10_2021 = {
    "A01": "Broken access control",
    "A02": "Cryptographic failures",
    "A03": "Injection",
    "A04": "Insecure design",
    "A05": "Security misconfiguration",
    "A06": "Vulnerable and outdated components",
    "A07": "Identification and authentication failures",
    "A08": "Software and data integrity failures",
    "A09": "Security logging and monitoring failures",
    "A10": "Server-side request forgery (SSRF)",
}

# MITRE ATT&CK Enterprise — all 14 tactics + curated techniques mapped to
# Virgent's detection rules.
_MITRE_ATTACK = {
    # tactics
    "TA0043": "Reconnaissance (tactic)",
    "TA0042": "Resource development (tactic)",
    "TA0001": "Initial access (tactic)",
    "TA0002": "Execution (tactic)",
    "TA0003": "Persistence (tactic)",
    "TA0004": "Privilege escalation (tactic)",
    "TA0005": "Defense evasion (tactic)",
    "TA0006": "Credential access (tactic)",
    "TA0007": "Discovery (tactic)",
    "TA0008": "Lateral movement (tactic)",
    "TA0009": "Collection (tactic)",
    "TA0011": "Command and control (tactic)",
    "TA0010": "Exfiltration (tactic)",
    "TA0040": "Impact (tactic)",
    # techniques
    "T1110": "Brute force",
    "T1110.003": "Brute force: password spraying",
    "T1078": "Valid accounts",
    "T1190": "Exploit public-facing application",
    "T1059": "Command and scripting interpreter",
    "T1059.004": "Command and scripting interpreter: Unix shell",
    "T1071": "Application layer protocol (C2)",
    "T1136": "Create account",
    "T1548": "Abuse elevation control mechanism",
    "T1548.003": "Abuse elevation control mechanism: sudo and sudo caching",
    "T1068": "Exploitation for privilege escalation",
    "T1046": "Network service discovery",
    "T1571": "Non-standard port",
    "T1552": "Unsecured credentials",
    "T1552.001": "Unsecured credentials: credentials in files",
    "T1195": "Supply chain compromise",
    "T1505": "Server software component",
    "T1562": "Impair defenses",
    "T1070": "Indicator removal",
    "T1499": "Endpoint denial of service",
}

# framework key -> (framework display name, entries, id-prefix)
_FRAMEWORKS: list[tuple[str, dict, str]] = [
    ("NIST-CSF-2.0", _NIST_CSF_20, "CSF:"),
    ("NIST-800-53", _NIST_800_53, "NIST:"),
    ("ISO27001", _ISO_27001_2022, "ISO27001:A."),
    ("SOC2", _SOC2_TSC, "SOC2:"),
    ("CIS-Controls-v8", _CIS_CONTROLS_V8, "CISC:"),
    ("CIS", _CIS_BENCHMARKS, "CIS:"),
    ("PCI-DSS-4.0", _PCI_DSS_40, "PCI:"),
    ("HIPAA", _HIPAA_SECURITY, "HIPAA:"),
    ("GDPR", _GDPR, "GDPR:"),
    ("OWASP-Top10", _OWASP_TOP10_2021, "OWASP:"),
    ("MITRE-ATTACK", _MITRE_ATTACK, "ATTACK:"),
]


def build_controls() -> dict[str, dict]:
    controls: dict[str, dict] = {}
    for framework, entries, prefix in _FRAMEWORKS:
        for suffix, title in entries.items():
            # ISO ids already carry the "A." theme in the suffix map keys
            cid = f"{prefix}{suffix}" if not prefix.endswith("A.") else f"ISO27001:{suffix}"
            controls[cid] = {"framework": framework, "title": title}
    return controls


CONTROLS: dict[str, dict] = build_controls()
